services:
  - type: web
    name: sweetvalues
    env: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: SweetValues
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://sweetvalues.onrender.com  # substituir pelo seu URL real
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: sweetvalues-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sweetvalues-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: sweetvalues-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: sweetvalues-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sweetvalues-db
          property: password
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        value: log
      - key: LOG_CHANNEL
        value: stderr
      - key: MAIL_FROM_ADDRESS
        value: noreply@sweetvalues.com
      - key: MAIL_FROM_NAME
        value: Sweet Values
      - key: ADMIN_NAME
        value: Admin
      - key: ADMIN_EMAIL
        value: riankarlosweber13@gmail.com
      - key: ADMIN_PASSWORD
        value: "102030405060"

databases:
  - name: sweetvalues-db
    plan: free
    databaseName: sweet_values_db
    user: svadmin
